name: My CI/CD Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set environment variable from secret
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

      - name: Use the API key
        run: |
          echo "Gemini API Key: $GEMINI_API_KEY"
          # Your deployment command or application startup that uses $GEMINI_API_KEY
          # For example, if using gcloud:
          # gcloud run deploy my-chatbot --image gcr.io/my-project/my-image --update-env-vars GEMINI_API_KEY="$GEMINI_API_KEY"